encoding:         UTF-8

markdown:         kramdown
kramdown:
  input:          GFM
  syntax_highlighter: rouge
# markdown:         redcarpet
redcarpet:
  extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      rouge

permalink:        none
version:          1.0.0

title:            "Mark Sanghoon Kim"
tagline:          "Empathy is Key"
description:      "A software engineer's blog with stories about his projects and his learning, as well as other thoughts on software engineering and web development."
keywords:         JavaScript, Web Components, DevTools, CSS, Mark Sanghoon Kim, Mark S Kim, marksanghoonkim.com, web development, MVC, blog, software, engineer, software engineer
url:              http://marksanghoonkim.com

author:
  name:           "Mark Sanghoon Kim"
  email:          mark.s.kim@gmail.com
  url:            http://marksanghoonkim.com

production_url:   http://marksanghoonkim.com

github:
  repo:           https://github.com/marksanghoonkim/marksanghoonkim.github.io

twitter:
  username:       marksanghoonkim

google_analytics: UA-69556458-1
