encoding:         UTF-8

#markdown:         kramdown
#kramdown:
#  input:          GFM
#  syntax_highlighter: rouge
markdown:         redcarpet
redcarpet:
  extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

permalink:        none
version:          1.0.0

title:            "Mark Sanghoon Kim"
tagline:          "Empathy is Key"
description:      "Empathy is Key"
url:              http://marksanghoonkim.com

author:
  name:           "Mark Sanghoon Kim"
  email:          mark.s.kim@gmail.com
  url:            http://marksanghoonkim.com

github:
  repo:           https://github.com/marksanghoonkim/marksanghoonkim.github.io

twitter:
  username:       marksanghoonkim

# google_analytics: UA-58296043-7
